title: MY PAGE
author: Selin Pinarer
email: s.pinarer@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  I want to make a blog to show my life, my ambitions and my projects. This is just the start.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
